modelcontextprotocol/kotlin-sdk

- src/main/kotlin/io/modelcontextprotocol/kotlin/sdk/types.kt
According to the schema https://github.com/modelcontextprotocol/specification/blob/main/schema/schema.json, tool's inputSchema should have 'required' field with a list of required property names.
> Add required field to tool input

- src/main/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/Protocol.kt
- src/main/kotlin/io/modelcontextprotocol/kotlin/sdk/types.kt
- src/main/kotlin/io/modelcontextprotocol/kotlin/sdk/types.util.kt
- src/test/kotlin/client/TypesTest.kt
This change updates the handling of `requestID` by accepting it as a string. This ensures greater flexibility and compatibility with varying input formats.
This change solves inconsistencies with the data type handling of `requestID` across different implementations, improving system robustness.
The change was tested in a controlled environment with various string inputs to verify compatibility and correctness. Scenarios with incorrect formats were tested to ensure proper error handling.
~No breaking changes are introduced.~
No additional context.
> Accept requestID as a string, fix #25

- src/main/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/Protocol.kt
Makes the error handling behavior consistent between Kotlin and TypeScript implementations when handling connection closure events.
> Fix the difference in error handling between Kotlin and Typescript implementations in onClose

- src/main/kotlin/io/modelcontextprotocol/kotlin/sdk/client/Client.kt
- src/main/kotlin/io/modelcontextprotocol/kotlin/sdk/server/Server.kt
- src/main/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/Protocol.kt
The generic types in the Protocol class were not providing significant value and made the code more complex. This change simplifies the API by removing these generic parameters while maintaining the same functionality.
another breaking change
> Drop generics from Protocol class

- api/kotlin-sdk.api
- build.gradle.kts
- gradle/libs.versions.toml
Add org.jetbrains.kotlinx.binary-compatibility-validator plugin
It is fixing issue #9 allowing to verify binary compatibility while this SDK is evolving. 
With gradle build generating apiDump
```shell
./gradlew apiDump
```
No
> Add org.jetbrains.kotlinx.binary-compatibility-validator plugin

- README.md
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/SSEClientTransport.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/server/Server.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/Transport.kt
> Migrate to kotlin style callbacks. Close #14

- .github/workflows/validate-pr.yml
GH doesn't allow to run `workflow_dispatch` events on forks, and another type of event is needed. This added trigger for the auto-merge event, and should solve the problem
> Enable auto-merge instead of merge queue

- build.gradle.kts
- gradle/libs.versions.toml
- src/commonTest/kotlin/ToolSerializationTest.kt
I added:
- `kotest-assertions-json` dependency
- `ToolSerializationTest` to verify correctness of tool serialization
This change does not provide any feature, except for improving test coverage. It paves the way for my subsequent PRs presenting JSON schema inputs which are valid and might appear in MCP, but cannot be expressed by the current `Tool.Input`.
See also:
* https://github.com/modelcontextprotocol/specification/issues/156
* #32 
It comes with the test itself.
No
> Add support for testing JSON serialization of the mcp API

- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/Protocol.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/types.kt
- src/jvmTest/kotlin/client/ClientTest.kt
Fixes issue #42 by setting the default to `JSONRPTCRequest.params` from null to `EmptyJsonObject`. This makes it so that the absence of params in a request is treated as an empty array which is what the Python sdk also does.
This makes it so that these two request bodies are treated similarly where previously not including params would result in an empty response.
`{"jsonrpc": "2.0", "method": "tools/list","params": {}, "id": 1}`
and 
`{"jsonrpc": "2.0", "method": "tools/list", "id": 1}`
I tested this with the sample Kotlin server project (with a bit of modification to update sample to use more up to date code) and a basic python SSE client.
I would use the python client to get the sessionId and then I would run
```
curl -v -X POST …
```
> Process JSONRPCRequest with default param (#42)

- samples/kotlin-mcp-server/build.gradle.kts
- samples/kotlin-mcp-server/src/main/kotlin/Main.kt
* Updates sample project to use library version 0.3.0
* Fixes ktor example by using `.start(wait = True)` similar to the plain config example
* updates function names to conform to the [kotlin style guide](https://kotlinlang.org/docs/coding-conventions.html) per the contribution guidelines (only test function names should use the backticks with spaces)
I realize there's not technically an issue on this but wasn't sure if a sample project update needed one but I wanted to try this library out but the sample was slightly outdated and the ktor example wasn't working so I updated it for my tests and figured I could put a PR to update in the project. Feel free to close this if this isn't appropriate as I'm not sure the procedure with sample updates 
I focused on the KTOR and plain config …
> Update sample project to use library version 0.3.0

- samples/kotlin-mcp-server/src/main/kotlin/Main.kt
Claude Desktop expects the following:
- No stdout emissions before the actual JSON interactions (removed the `Server running...` text)
- Tool name to conform to a regex:
This PR makes the required changes to the example project.
After these changes, both MCP inspector and Claude Desktop behave correctly:
> Change sample to work with Claude Desktop

- build.gradle.kts
Update target to Java 8
Support consumers that are compiling against Java 8
Ensured that the build succeeds
No known breaking changes
> Support consumers that require Java 8

- samples/weather-stdio-server/src/main/kotlin/io/modelcontextprotocol/sample/server/McpWeatherServer.kt
Fixed according to [this comment
](https://github.com/modelcontextprotocol/docs/pull/178#discussion_r1993270466)
Locally
No breaking changes
> Remove CompletableDeferred from weather-stdio-server sample

- samples/kotlin-mcp-server/src/main/kotlin/Main.kt
- samples/weather-stdio-server/src/main/kotlin/io/modelcontextprotocol/sample/server/McpWeatherServer.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/server/Server.kt
- src/jvmTest/kotlin/InMemoryTransport.kt
- src/jvmTest/kotlin/client/InMemoryTransportTest.kt
Removed the mention of `onCloseCallback`, and replaced all uses of `onCloseCallback` to `onClose`.
Refactor the code to the 0.4.0 version of sdk
Tested locally:
- ran all tests
- ran projects in samples
No breaking changes
> remove the mention of `onCloseCallback` and replace it  to `onClose`

- samples/weather-stdio-server/src/main/kotlin/io/modelcontextprotocol/sample/server/McpWeatherServer.kt
JSON object construction for input schemas using `buildJsonObject`
Simplify code
Locally
No breaking changes
> Refactor for simplify input schemas

- build.gradle.kts
- gradle/libs.versions.toml
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/SSEClientTransport.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/StdioClientTransport.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/server/SSEServerTransport.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/server/StdioServerTransport.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/WebSocketMcpTransport.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/types.kt
- update Kotlin version to 2.1.20
- use atomics from `kotlin.concurrent`
- refactor lock in `StrdioServerTransport`, using `Channel`
- remove the `atomicfu` plugin
- unit test
- run a custom mcp server with Claude via stdio
No breaking changes
default atomics: https://kotlinlang.org/docs/whatsnew2120.html#common-atomic-types
> Update to Kotlin 2.1.20 and minor refactoring

- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/ReadBuffer.kt
- src/jvmTest/kotlin/shared/ReadBufferTest.kt
This pull request fixes an issue with the `ReadBuffer` functionality by ensuring that empty lines are properly skipped during input processing. A new test case has been added to validate this behavior.
The `ReadBuffer` threw exception on empty message which leaded to connection closing.
no
> Skip empty lines

- samples/kotlin-mcp-server/build.gradle.kts
Add jar config to build aplication with correct `Main-Class` into `MANIFEST.MF`.
Fix build.gradle.kts to generate correct jar file. 
I received error to run jar and I was not able to run the Example MCP Server in Kotlin.
I ran the java initialization prompt command into MCP Documentation and worked after the fix.
> Fix jar build configuration

- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/types.kt
- src/commonTest/kotlin/ToolSerializationTest.kt
Snake case is expected in general in Anthropic and other LLM provider,  so serialize `Tool.inputSchema` as `input_schema` 
Tool class can be used directly in message API, but it needs to be snake case
Tests are updated and passing, also according to https://docs.anthropic.com/en/api/messages#body-tools
If code depends on camlCase, then this is a breaking change.
> fix(client): serialize inputSchema as input_schema

- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/types.kt
- src/commonTest/kotlin/ToolSerializationTest.kt
`type` in `Tool.Input` has a default value, but the spec doesn't treat it as default value, therefore serailizer  should always write it. 
Serialized `Tool` can be used directly in calling anthropic api (without SDK).
Passing all existing tests
It is a breaking change if code depends on "missing" `type` behavior
> fix(client) add encodeDefault for field with non spec default value

- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/SSEClientTransport.kt
fixes: #63
Adds the missing `requestBuilder` call to `send` function
Client doesn't send `Auth` headers when sending a rpc message
logs:
```sh
2025-05-05 01:07:32.569 12997-13028            V  REQUEST: https://[REDACTED]/sse/message?sessionId=c28e21031144b7b85616b23d6caf8c7feb1f88e88ad1beefb533b68060d3e236
METHOD: POST
COMMON HEADERS
-> Accept: application/json
-> Accept-Charset: UTF-8
-> Authorization: Bearer e41ef9271332d4732fb4f[REDACTED]
CONTENT HEADERS
-> Content-Length: 230
-> Content-Type: application/json
2025-05-05 01:07:32.594 12997-13028            D  tagSocket(114) with statsTag=0xffffffff, statsUid=-1
2025-05-05 01:07:33.097 12997-13055            V  RESPONSE: 202 Accepted
METHOD: POST
FROM: https://[REDACTED]/sse/message?sessionId=c28e21031144b7b85616b23d6caf8c7feb1f88e88ad1b …
```
> fix: apply `requestBuilder` headers when sending rpc messages

- api/kotlin-sdk.api
- gradle/libs.versions.toml
update:
- kotlin 2.2.0
- ktor 3.1.3 — Version 3.2.0 is already out, but it has a regression with Android
> update kotlin to 2.2.0 and ktor to 3.1.3

- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/SSEClientTransport.kt
- src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/integration/SseIntegrationTest.kt
Remove the hardcoded /sse string in the sse client transport, which forcibly adds /sse to the path, making it very crude. 
When using all sse mcp servers, it's almost always in the format like `http://localhost:3000/sse`, and the forced addition of /sse leads to errors. In (npx @modelcontextprotocol/inspector), users also need to manually add the /sse suffix.
If this PR is merged, consumers must manually add the /sse suffix to their URL.
> Remove fixed suffix /sse

- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/SSEClientTransport.kt
- src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/client/SseTransportTest.kt
issue is : https://github.com/modelcontextprotocol/kotlin-sdk/issues/41
mcp sse server does not remove last path when join endpoint url.
for example: baseUrl is http://localhost/sse, and server return sse data:
event:endpoint data:mesages?sessionId=a7f13c57-3ebe-4676-8079-bab962990583
sdk return endpoint http://localhost/sse/mesages?sessionId=a7f13c57-3ebe-4676-8079-bab962990583
the correct endpoint should be http://localhost/mesages?sessionId=a7f13c57-3ebe-4676-8079-bab962990583
python-sdk can correctly return the endpoint
> sse server does not process endpoint correctly when sse path is not a directory

- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/SSEClientTransport.kt
- src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/client/SseTransportTest.kt
- src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/integration/SseIntegrationTest.kt
- cancellation exception
- clean up code
locally
no
> refactor `SseClientTransport`

- api/kotlin-sdk.api
- build.gradle.kts
- gradle/libs.versions.toml
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/Client.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/server/Server.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/Protocol.kt
#117 
Using atomic and persistent collections for thread safety and optimal performance. And to preserve the current API
locally
No
There were several solutions to this problem:
- using a mutex, but that would require changing the current functions to suspend, which was problematic for some functions and would introduce breaking changes
- using internal `ConcurrentMap` from ktor, which is not recommended for use
- using `atomic` and `kotlinx-collections-immutable`. However, `kotlinx-collections-immutable` is in alpha, which also introduces risks for usage
> atomic and persistent collections for thread safety

- api/kotlin-sdk.api
- build.gradle.kts
- gradle/libs.versions.toml
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/StreamableHttpClientTransport.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/StreamableHttpMcpKtorClientExtensions.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/types.kt
- src/jvmTest/kotlin/client/StreamableHttpClientTransportTest.kt
> Add streamable http client transport

- .github/workflows/gradle-publish.yml
- build.gradle.kts
- gradle.properties
> Update CI workflows configuration for debugging

- api/kotlin-sdk.api
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/server/Server.kt
- src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/types.kt
- src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/ToolSerializationTest.kt
- src/jvmTest/kotlin/client/ClientTest.kt
Add missing title property to tool object
Allow to provide a title property for a tool that is supported by LLM and is used for displaying the tool name.
New serialization/deserialization tests are added.
No. This is an optional parameter. The fix should not break user's code.
> Add optional title property for tool object (#191)

- buildSrc/src/main/kotlin/mcp.jreleaser.gradle.kts
- buildSrc/src/main/kotlin/mcp.publishing.gradle.kts
> Update MavenCentral configuration and developer metadata

- kotlin-sdk-core/src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/types.util.kt
- kotlin-sdk-core/src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/RequestSerializerTest.kt
Fixes: https://github.com/modelcontextprotocol/kotlin-sdk/issues/233
The issue appeared due to fallback-style `RequestResultPolymorphicSerializer` implementation: 
```
internal object ServerResultPolymorphicSerializer :
JsonContentPolymorphicSerializer<ServerResult>(ServerResult::class) {
override fun selectDeserializer(element: JsonElement): DeserializationStrategy<ServerResult> =
selectServerResultDeserializer(element)
?: EmptyRequestResult.serializer()
}
internal object ClientResultPolymorphicSerializer :
JsonContentPolymorphicSerializer<ClientResult>(ClientResult::class) {
override fun selectDeserializer(element: JsonElement): DeserializationStrategy<ClientResult> =
selectClientResultDeserializer(element)
?: EmptyRequestResult.serializer()
}
internal object …
```
> Fix serializer for CreateElicitationResult

- .github/workflows/build.yml
> Fix upload reports in GitHub actions

- kotlin-sdk-test/src/jvmTest/kotlin/io/modelcontextprotocol/kotlin/sdk/integration/typescript/TypeScriptClientKotlinServerTest.kt
Ignore flaky `testMultipleClientParallel`
> Mark `testMultipleClientParallel` as ignored due to flakiness

- buildSrc/src/main/kotlin/mcp.multiplatform.gradle.kts
- kotlin-sdk-client/api/kotlin-sdk-client.api
- kotlin-sdk-core/build.gradle.kts
- kotlin-sdk-server/api/kotlin-sdk-server.api
> Move `generateLibVersion` task to `kotlin-sdk-core` 

- build.gradle.kts
- buildSrc/src/main/kotlin/mcp.publishing.gradle.kts
- gradle/libs.versions.toml
- kotlin-sdk/src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/package.kt
- test new publish plugin
- add package.kt to kotlin-sdk umbrella module to resolve klib generation errors during Maven publishing
no
> Prerelease 0.7.2-alpha1

- buildSrc/src/main/kotlin/mcp.publishing.gradle.kts
Add a new function for signing publications
In the [latest release build](https://github.com/modelcontextprotocol/kotlin-sdk/actions/runs/17830036899/job/50692417727), the artifact signing tasks were not included
no
> Refactor signing publications

- kotlin-sdk-core/build.gradle.kts
Moves capture of the project version to execution time to avoid a gradle configuration cache issue
Improves support for configuration cache
Its been tested locally and removes the gradle warning
N/A
> Capture version at configuration time to avoid configuration cache issue
